IF OBJECT_ID('[dbo].[newproc]') IS NOT NULL
	DROP PROCEDURE [dbo].[newproc];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
--Author: RED-GATE\Anderson.Rangel
--Date: 1/09/2020

CREATE PROCEDURE [dbo].[newproc]
    @parameter_name AS INT
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'
AS
begin
    SELECT * FROM dbo.DM_CREDIT_CARD_TYPE AS DCCT
end
GO
