IF OBJECT_ID('[dbo].[oldview]') IS NOT NULL
	DROP VIEW [dbo].[oldview];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--Author: RED-GATE\Anderson.Rangel
--Date: 2/09/2020
CREATE VIEW [dbo].[oldview]
--WITH ENCRYPTION, SCHEMABINDING, VIEW_METADATA
AS
    SELECT * FROM dbo.DM_CUSTOMER_ASXML_IDAttr AS DCAIA
-- WITH CHECK OPTION
GO
